##
##
# Declare the routing rules to reach the backend #
##
##

---
kind: TLSRoute
apiVersion: gateway.networking.k8s.io/v1alpha3
metadata:
  name: tlsroute-whoami
  namespace: traefik
spec:
  parentRefs:
    # Attach the route to the by-default Traefik Gateway
    - name: traefik-gateway-tls
      kind: Gateway
      group: gateway.networking.k8s.io
  # Define the hostname
  hostnames:
    - "whoami-tls.docker.localhost"
  rules:
    - backendRefs:
        - name: whoami-tls
          port: 8443
          weight: 1
          kind: Service
          group: ""
