---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-with-nginx-annotation
  namespace: traefik
  annotations:
    # BASIC
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret-type: "auth-file"
    nginx.ingress.kubernetes.io/auth-secret: "traefik/basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: "Ingress-NGINX BASIC Auth"
    # SSL Redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # Optional because true by default
spec:
  ingressClassName: nginx
  rules:
    - host: whoami-tls.docker.localhost
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: whoami
                port:
                  number: 80
  tls:
    -  hosts:
        - whoami-tls.docker.localhost
       secretName: external-certs