##
##
# Declare the routing rules to reach the backend #
##
##
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: httproute-whoami-tls
  namespace: team01
spec:
  parentRefs:
    # Attach the route to the by-default Traefik Gateway
    - name: traefik-gateway
      kind: Gateway
      namespace: traefik
      sectionName: websecure
      group: gateway.networking.k8s.io
  # Define the hostname
  hostnames:
    - "team01.docker.localhost"
  rules:
    - backendRefs:
        - name: whoami
          namespace: team01
          port: 80
          kind: Service
          group: ""